inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'db/seeds.rb'
    - 'lib/tasks/forms.rake'

Layout/LineLength:
  Exclude:
    - 'db/migrate/20210317003722_devise_create_users.rb'
  Max: 90

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Max: 21
  Exclude:
    - 'db/migrate/*.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false
